# Generated by Django 5.2.15 on 2026-06-16 13:36

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("engagement", "0002_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="body",
            field=common.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name="review",
            name="title",
            field=common.fields.EncryptedCharField(blank=True),
        ),
    ]
