# Generated by Django 5.2.15 on 2026-06-11 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "handle",
                    models.SlugField(
                        help_text="URL slug, e.g. 'cinematic'.", unique=True
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("image", models.URLField(blank=True, help_text="Cover image URL.")),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers sort first."
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "handle",
                    models.SlugField(
                        help_text="URL slug, e.g. 'midnight-noir'. Also the S3 file name.",
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                (
                    "product_type",
                    models.CharField(
                        choices=[("LUT Pack", "LUT Pack"), ("Bundle", "Bundle")],
                        default="LUT Pack",
                        max_length=40,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "compare_at_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional 'was' price to show a discount.",
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("vendor", models.CharField(default="Luts.shop", max_length=80)),
                (
                    "best_for",
                    models.CharField(
                        blank=True,
                        help_text="Bold use-case lead on cards, e.g. 'moody vlogs and rainy-day b-roll'.",
                        max_length=200,
                    ),
                ),
                (
                    "lut_count",
                    models.PositiveIntegerField(
                        default=1, help_text="LUTs in this pack."
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated, e.g. 'mobile, capcut, vlog, moody'. Add 'free' for the weekly free LUT.",
                        max_length=240,
                    ),
                ),
                (
                    "formats",
                    models.CharField(
                        default=".cube", help_text="Comma-separated.", max_length=120
                    ),
                ),
                (
                    "compatible_apps",
                    models.CharField(
                        default="Premiere Pro,DaVinci Resolve,Final Cut,CapCut",
                        help_text="Comma-separated.",
                        max_length=240,
                    ),
                ),
                (
                    "featured_image_url",
                    models.URLField(help_text="Main product/preview image."),
                ),
                ("featured_image_alt", models.CharField(blank=True, max_length=200)),
                (
                    "before_image_url",
                    models.URLField(
                        blank=True, help_text="Ungraded frame (before/after slider)."
                    ),
                ),
                (
                    "after_image_url",
                    models.URLField(
                        blank=True, help_text="Graded frame (enables the slider)."
                    ),
                ),
                (
                    "preview_video_url",
                    models.URLField(
                        blank=True, help_text="Optional looping preview clip."
                    ),
                ),
                (
                    "file_key",
                    models.CharField(
                        blank=True,
                        help_text="Private S3 object key. Blank = 'luts/<handle>.zip'.",
                        max_length=200,
                    ),
                ),
                (
                    "featured",
                    models.BooleanField(
                        default=False, help_text="Float to the top of listings."
                    ),
                ),
                (
                    "available",
                    models.BooleanField(
                        default=True, help_text="Uncheck to mark sold-out."
                    ),
                ),
                (
                    "published",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to hide from the store (draft).",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers sort first."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "collections",
                    models.ManyToManyField(
                        blank=True, related_name="products", to="catalog.collection"
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="IncludedLut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "tone",
                    models.CharField(help_text="Short coloring note.", max_length=200),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="included_luts",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("alt", models.CharField(blank=True, max_length=200)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_images",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
    ]
