# Generated by Django 5.2.15 on 2026-06-11 02:36

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="featured_image_file",
            field=models.FileField(
                blank=True,
                help_text="Upload the main image.",
                upload_to=catalog.models.media_upload_to,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="lut_file",
            field=models.FileField(
                blank=True,
                help_text="Upload the downloadable LUT pack (.zip, or a single .cube — it's zipped for you).",
                upload_to=catalog.models.lut_upload_to,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="preview_video_file",
            field=models.FileField(
                blank=True,
                help_text="Upload a looping preview clip (mp4).",
                upload_to=catalog.models.media_upload_to,
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="image",
            field=models.FileField(
                blank=True,
                help_text="Upload an image.",
                upload_to=catalog.models.media_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="featured_image_url",
            field=models.URLField(
                blank=True, help_text="Main image URL (or upload a file below)."
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="file_key",
            field=models.CharField(
                blank=True,
                help_text="Private S3 object key. Auto-set when you upload; blank = 'luts/<handle>.zip'.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="preview_video_url",
            field=models.URLField(
                blank=True, help_text="Looping preview clip URL (or upload below)."
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="url",
            field=models.URLField(
                blank=True, help_text="Image URL (or upload a file)."
            ),
        ),
    ]
