# Generated by Django 5.2.15 on 2026-06-11 02:49

import catalog.models
import catalog.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_featured_image_file_product_lut_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="bundled_products",
            field=models.ManyToManyField(
                blank=True,
                help_text="Bundles only: the packs included in this bundle.",
                related_name="in_bundles",
                to="catalog.product",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="featured_image_file",
            field=models.FileField(
                blank=True,
                help_text="Upload the main image (jpg/png/webp, ≤15 MB).",
                upload_to=catalog.models.media_upload_to,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp", "gif", "avif"]
                    ),
                    catalog.validators.MaxFileSizeValidator(15),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="lut_file",
            field=models.FileField(
                blank=True,
                help_text="Upload the downloadable LUT pack (.zip/.cube/.3dl, ≤200 MB). A single .cube is zipped for you.",
                upload_to=catalog.models.lut_upload_to,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["zip", "cube", "3dl"]
                    ),
                    catalog.validators.MaxFileSizeValidator(200),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="preview_video_file",
            field=models.FileField(
                blank=True,
                help_text="Upload a looping preview clip (mp4/webm, ≤100 MB).",
                upload_to=catalog.models.media_upload_to,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["mp4", "webm", "mov"]
                    ),
                    catalog.validators.MaxFileSizeValidator(100),
                ],
            ),
        ),
    ]
