# Generated by Django 5.2.15 on 2026-06-13 14:28

import catalog.models
import catalog.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_product_bundled_products_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="featured_image_cdn_key",
            field=models.CharField(blank=True, editable=False, max_length=300),
        ),
        migrations.AddField(
            model_name="product",
            name="preview_hls_key",
            field=models.CharField(blank=True, editable=False, max_length=300),
        ),
        migrations.AddField(
            model_name="product",
            name="preview_poster_key",
            field=models.CharField(blank=True, editable=False, max_length=300),
        ),
        migrations.AddField(
            model_name="product",
            name="transcode_job_id",
            field=models.CharField(blank=True, editable=False, max_length=120),
        ),
        migrations.AddField(
            model_name="product",
            name="transcode_status",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="MediaConvert job status (SUBMITTED → PROGRESSING → COMPLETE/ERROR).",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="preview_video_file",
            field=models.FileField(
                blank=True,
                help_text="Upload a looping preview clip (mp4/webm, ≤100 MB). Auto-transcoded to adaptive HLS for smooth, low-cost streaming.",
                upload_to=catalog.models.media_upload_to,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["mp4", "webm", "mov"]
                    ),
                    catalog.validators.MaxFileSizeValidator(100),
                ],
            ),
        ),
    ]
