# Generated by Django 5.2.15 on 2026-06-10 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_confirmation_email_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="refunded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
