# Generated by Django 5.2.15 on 2026-06-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_refunded_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="review_request_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
