# Generated by Django 5.2.15 on 2026-06-10 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0002_downloadgrant_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="downloadgrant",
            name="revoked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
