# Generated by Django 5.2.15 on 2026-06-10 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session", models.CharField(db_index=True, max_length=64)),
                ("name", models.CharField(db_index=True, max_length=32)),
                ("path", models.CharField(blank=True, max_length=300)),
                ("product_handle", models.CharField(blank=True, max_length=255)),
                ("referrer", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["name", "created_at"],
                        name="analytics_e_name_6ca12c_idx",
                    )
                ],
            },
        ),
    ]
