# Generated by Django 5.2.15 on 2026-06-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL: /blog/<slug>.", max_length=220, unique=True
                    ),
                ),
                (
                    "excerpt",
                    models.CharField(
                        help_text="One- or two-sentence summary — shown on cards and used as the SEO meta description.",
                        max_length=300,
                    ),
                ),
                ("body", models.TextField(help_text="Post content in Markdown.")),
                (
                    "cover_image_url",
                    models.URLField(
                        blank=True,
                        help_text="Cover image (used on the card + Open Graph).",
                    ),
                ),
                (
                    "author_name",
                    models.CharField(default="The Looks Lab", max_length=120),
                ),
                (
                    "published",
                    models.BooleanField(
                        default=False, help_text="Tick to make the post live on /blog."
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Auto-set when first published.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-published_at", "-created_at"],
            },
        ),
    ]
